-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS O
LEFT JOIN PRODUCT AS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;